[package]
name = "frm-midw"
version = "0.1.0"
edition = "2021"

[dependencies]
stb_image = "0.3"
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[build-dependencies]
bindgen = "0.69.1"
