[package]
name = "jpg-recognition"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
engine = { workspace = true, features = ["image"] }
anyhow.workspace = true
image = "0.24"
